var myName = "Adam";
console.log("Is myName == 'Adam'? | I predict True");
console.log(myName == "Adam");
var companyName = "Siemens";
console.log("Is companyName == 'Siemens'? | I predict True");
console.log(companyName == "Siemens");
var friendName = "Asfandyaar";
console.log("Is friendName == 'Sameer'? | I predict False");
console.log(friendName == "Sameer");
var brand = "Toyota";
console.log("Is brand == 'Mercedes'? | I predict False");
console.log(brand == "Mercedes");
var shopName = "Walmart";
console.log("Is shopName == 'Spar'? | I predict False");
console.log(shopName == "Spar");
var fruit = "Pear";
console.log("Is fruit == 'Apple'? | I predict False");
console.log(fruit == "Apple");
var input = "1234";
console.log("Is input == '1234'? | I predict True");
console.log(input == "1234");
var balance = "$55000";
console.log("Is balance == '$60000'? | I predict False");
console.log(balance == "S60000");
var utensil = "Spoon";
console.log("Is utensil == 'Spoon'? | I predict True");
console.log(utensil == "Spoon");
var drink = "Cola";
console.log("Is drink == 'Cola'? | I predict True");
console.log(drink == "Cola");
